name: Build Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [x64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      shell: bash
      run: |
        if [ $RUNNER_OS == "Linux" ]; then
          sudo apt-get update
          if [ ${{ matrix.architecture }} == "x64" ]; then
            sudo apt-get install -y g++
          else
            sudo apt-get install -y gcc-aarch64-linux-gnu
          fi
        elif [ $RUNNER_OS == "Windows" ]; then
          if [ ${{ matrix.architecture }} == "x64" ]; then
            choco install mingw
          fi
        elif [ $RUNNER_OS == "macOS" ]; then
          if [ ${{ matrix.architecture }} == "x64" ]; then
            brew install gcc
          else
            brew install llvm
            brew install arm-none-eabi-gcc
            export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
          fi
        fi

    - name: Build
      shell: bash
      run: |
        if [ $RUNNER_OS == "Linux" ]; then
          if [ ${{ matrix.architecture }} == "x64" ]; then
            g++ -o output main.cpp
          else
            aarch64-linux-gnu-g++ -o output main.cpp
          fi
        elif [ $RUNNER_OS == "Windows" ]; then
          g++ -o output main.cpp
        elif [ $RUNNER_OS == "macOS" ]; then
          if [ ${{ matrix.architecture }} == "x64" ]; then
            g++ -o output main.cpp
          else
            arm-none-eabi-g++ -o output main.cpp
          fi
        fi
