name: Build Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [x64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      shell: bash
      run: |
        case "${{ matrix.os }}-${{ matrix.architecture }}" in
          "ubuntu-latest-x64")
            sudo apt-get update
            sudo apt-get install -y g++
            ;;
          "ubuntu-latest-arm64")
            sudo apt-get update
            sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
            ;;
          "windows-latest-x64")
            choco install mingw
            ;;
          "macos-latest-x64")
            brew install gcc
            ;;
          "macos-latest-arm64")
            brew install llvm
            brew install gcc
            export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
            ;;
        esac

    - name: Build
      shell: bash
      run: |
        case "${{ matrix.os }}-${{ matrix.architecture }}" in
          "ubuntu-latest-x64")
            g++ -o output main.cpp
            ;;
          "ubuntu-latest-arm64")
            aarch64-linux-gnu-g++ -o output main.cpp
            ;;
          "windows-latest-x64")
            g++ -o output main.cpp
            ;;
          "macos-latest-x64")
            g++ -o output main.cpp
            ;;
          "macos-latest-arm64")
            g++ -o output main.cpp
            ;;
        esac


    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: potential-meme-${{ matrix.os }}-${{ matrix.architecture }}
        path: potential-meme
